pr: none
trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: choreo-samples

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pyyaml
      pip install requests
    displayName: 'Install dependencies'

  - script: python .azure/scripts/process_metadata.py 
    displayName: 'Run metadata extraction script'

  - task: AzureCLI@2
    displayName: Upload files to Azure Storage Account
    inputs:
      azureSubscription: $(resource_group)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "[INFO] staging directory"
        tree $(Build.StagingDirectory)
        echo "===================================="
        echo

        echo "[INFO] uploading files to Azure Storage Account"
        az storage blob upload-batch \
          --account-name "$(storage_account_name)" \
          -s "$(Build.StagingDirectory)" \
          -d "choreo-samples" \
          --overwrite true
        
        echo "[INFO] purging CDN endpoint"
        az cdn endpoint purge \
          --content-paths '/*'\
          --profile-name "$(cdn_profile)" \
          --name "$(cdn_endpoint)" \
          --resource-group "$(resource_group)"
  
  - script: |
      az storage blob download \
        --account-name "$(storage_account_name)" \
        --container-name "choreo-samples" \
        --name "choreo-samples-version.txt" \
        --file "local-version.txt" \
        --auth-mode login
      SAMPLES_VERSION=$(cat local-version.txt)
      echo "##vso[task.setvariable variable=SAMPLES_VERSION]$SAMPLES_VERSION"
    displayName: 'Get samples version'
  
  - template: update-image-in-cp-overlays.yml@common-templates
    parameters:
      CONFIGS:
        - CHOREO_SAMPLES_VERSION='$(SAMPLES_VERSION)'
